[config]
schemaVersion = "0.0.1"

[package]
namespace = "Spyci"
name = "LobbyKit"
versionNumber = "1.0.0"
description = "Host and lobby quality-of-life tools for Sledding Game: bigger lobbies, saved lobby/search settings, player timers, MOTD, and teleport commands."
websiteUrl = "https://github.com/ricky-davis/SGLobbyKit"
containsNsfwContent = false

[package.dependencies]
LavaGang-MelonLoader = "0.7.3"

[build]
icon = "./images/icon_256.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "LobbyKit/bin/Release/net6.0/LobbyKit.dll"
target = "/"

[[build.copy]]
source = "CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["sledding-game"]

[publish.categories]
sledding-game = ["tools", "mods"]
