<Project>
  <PropertyGroup>
    <WindowsGamePath>C:\Program Files (x86)\Steam\steamapps\common\Sledding Game</WindowsGamePath>
    <LinuxGamePath>/mnt/c/Program Files (x86)/Steam/steamapps/common/Sledding Game</LinuxGamePath>

    <GamePath Condition="'$(GamePath)' == '' and Exists('$(WindowsGamePath)')">$(WindowsGamePath)</GamePath>
    <GamePath Condition="'$(GamePath)' == '' and Exists('$(LinuxGamePath)')">$(LinuxGamePath)</GamePath>
    <GamePath Condition="'$(GamePath)' == ''">$(WindowsGamePath)</GamePath>

    <DeployMod Condition="'$(DeployMod)' == '' and '$(OS)' == 'Windows_NT'">true</DeployMod>
    <DeployMod Condition="'$(DeployMod)' == ''">false</DeployMod>
  </PropertyGroup>
</Project>
